spring.application.name=backend

# Production Database (Render -> Neon)
spring.datasource.url=jdbc:postgresql://ep-lively-hall-apacn4ik-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_2RzmCWbs8vTN&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2RzmCWbs8vTN

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhirampetta529@gmail.com
spring.mail.password=loaizyxrrdnezdjh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true